name: CI (Build & Test)

on:
  pull_request:
    branches: [ "main", "develop" ]   # main/develop로 PR 올릴 때 CI 실행

jobs:
  ci:
    runs-on: ubuntu-latest            # GitHub 제공 Ubuntu 러너에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v4     # 소스코드 내려받기

      - name: Set up JDK 21
        uses: actions/setup-java@v4   # 자바 설치
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"             # Gradle 캐시로 속도 향상

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew         # gradlew 실행 권한 부여

      - name: Run tests
        run: ./gradlew test           # 테스트

      - name: Build bootJar
        run: ./gradlew clean bootJar  # 실행 가능한 jar 생성
